apiVersion: apps/v1
kind: Deployment
metadata:
    name: microscale-deployment
    labels:
        app: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
          app: microscale-deployment
    template:
        metadata:
          labels:
            app: microscale-deployment
        spec:
            containers:
              - name: users
                image: TODO
                ports:
                - containerPort: 8002
              - name: storage
                image: TODO
                ports:
                - containerPort: 8001
              - name: worker
                image: TODO
              - name: frontend
                image: TODO
                ports:
                - containerPort: 8000
